server:
  port: 8080
  
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: JODConverter Sample Rest Api

springdoc:
  show-actuator: false
  api-docs:
    path: /rest/api
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages

logging:
  level:
    org.jodconverter: debug
