server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: JODConverter Sample Rest Api

springdoc:
  show-actuator: false
  api-docs:
    path: /rest/api
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
    process-retry-interval: 1000
    # ↑ delay, in milliseconds, between each try when trying to execute an office process call (start/terminate).
    max-tasks-per-process: 20
    # ↑ the maximum number of tasks an office process can execute before restarting
    task-queue-timeout: 60000
    # ↑ maximum living time of a task in the conversion queue, 60 secs
    template-profile-dir: /tmp/jodconverter
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages

logging:
  level:
    org.jodconverter: debug
